# Generated by Django 2.2.4 on 2020-12-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fav_books', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='default desc'),
            preserve_default=False,
        ),
    ]
